#!/bin/bash
# Runs the instances of the examples folder.

IN_PATH=$SUNNY_HOME/test/examples
OZN=$IN_PATH/tmp.ozn
cd $IN_PATH

for m in `ls *.mzn`
do
  echo "Solving $m....."
  if 
    [[ $m == 'domino.mzn' ]]
  then
    for d in domino.1.dzn domino.2.dzn
    do
       mzn2fzn $m $d --output-ozn-to-file $OZN
       sunny-cp -T 30 $m $d | solns2out $OZN | solns2dzn -l
       ret=$?
       if
         [ $ret -ne 0 ]
       then
         echo "Error while solving $m!!! Test aborted."
         exit $ret
       fi
    done
  else
    mzn2fzn $m --output-ozn-to-file $OZN
    sunny-cp -T 30 $m | solns2out $OZN | solns2dzn -l
    ret=$?
    if
      [ $ret -ne 0 ]
    then
      echo "Error while solving $m!!! Test aborted."
      rm *.fzn
      exit $ret
    fi
  fi
  echo "$m sucessfully tested!!!"
  echo -e "==========\n"
done
rm *.fzn
rm $OZN
echo "All went well!!! Test passed."
