#!/bin/bash
# Runs the instances of the test/examples folder.

IN_PATH=`dirname "$(readlink -f ${BASH_SOURCE[0]})"`
FZN=$IN_PATH/tmp.fzn
OUT=$IN_PATH/out
ERR=$IN_PATH/err
CORES=2
TIMEOUT=10
OUTPUT=$IN_PATH/output.log
ERRORS=$IN_PATH/errors.log
cd $IN_PATH
echo '' > $OUTPUT 
echo '' > $ERRORS

for m in `ls *.mzn | grep -v model`
do
  cmd="timeout $TIMEOUT sunny-cp -p $CORES -T $TIMEOUT $m"
  echo "Testing $m"
  echo "Command: $cmd"
  timeout $TIMEOUT sunny-cp -p $CORES -T $TIMEOUT $m 1>$OUT 2>$ERR
  ret=$?
  cat $OUT | grep -v %
  echo '********** Command: '$cmd >> $OUTPUT
  echo '********** Command: '$cmd >> $ERRORS
  cat $OUT >> $OUTPUT
  cat $ERR >> $ERRORS
  if
    [ $ret -ne 0 ]
  then
    if
      [ $ret -eq 124 ]
    then
      echo "Timeout while solving $m!!!"
    else
      echo "Error while solving $m!!! Test aborted."
      echo "Have a look at the log files $OUTPUT and $ERRORS"
      exit $ret
    fi
  fi
    
  echo -e "$m processed!\n"
  sleep 0.1
done
rm $OZN $OUT $ERR
rm *.fzn *.ozn 2>/dev/null
echo "All the examples processed without errors."
echo "Have a look at the log files $OUTPUT and $ERRORS"
