#!/bin/bash
# Runs the instances of the test/examples folder.

IN_PATH=`dirname "$(readlink -f ${BASH_SOURCE[0]})"`
OZN=$IN_PATH/tmp.ozn
OUT=$IN_PATH/out
ERR=$IN_PATH/err
CORES=2
TIMEOUT=10
OUTPUT=$IN_PATH/output.log
ERRORS=$IN_PATH/errors.log
cd $IN_PATH
rm $OUTPUT $ERRORS 2>/dev/null

for m in `ls *.mzn`
do
  echo "Solving $m....."
  if 
    [[ $m == 'domino.mzn' ]]
  then
    for d in domino.1.dzn domino.2.dzn
    do
      mzn2fzn $m $d --output-ozn-to-file $OZN -o /dev/null/foo
      cmd="timeout $TIMEOUT sunny-cp --check-solvers g12lazyfd,g12fd,g12cbc,g12fd -p $CORES -T $TIMEOUT --g12 $m $d"
      $cmd 1>$OUT 2>$ERR
      ret=$?
      cat $OUT | solns2out $OZN | grep -v %
      echo '********** Instance: '$cmd >> $OUTPUT
      echo '********** Instance: '$cmd >> $ERRORS
      cat $OUT >> $OUTPUT
      cat $ERR >> $ERRORS
      if
        [ $ret -ne 0 ]
      then
        if
          [ $ret -eq 124 ]
        then
          echo "Timeout while solving $m!!!"
        else
	  echo "Error while solving $m!!! Test aborted."
	  echo "Have a look at the log files $OUTPUT and $ERRORS"
	  exit $ret
        fi
      fi
    done
  else
    mzn2fzn $m --output-ozn-to-file $OZN -o /dev/null/foo
    cmd="timeout $TIMEOUT sunny-cp --check-solvers g12lazyfd,g12fd,g12cbc,g12fd -p $CORES -T $TIMEOUT --g12 $m"
    $cmd 1>$OUT 2>$ERR
    ret=$?
    cat $OUT | solns2out $OZN | grep -v %
    echo '********** Instance: '$cmd >> $OUTPUT
    echo '********** Instance: '$cmd >> $ERRORS
    cat $OUT >> $OUTPUT
    cat $ERR >> $ERRORS
    if
      [ $ret -ne 0 ]
    then
      if
        [ $ret -eq 124 ]
      then
        echo "Timeout while solving $m!!!"
      else
	echo "Error while solving $m!!! Test aborted."
	echo "Have a look at the log files $OUTPUT and $ERRORS"
	exit $ret
      fi
    fi
  fi
  echo -e "$m processed!\n"
done
rm $OZN $OUT $ERR
rm *.fzn *.ozn 2>/dev/null
echo "All the examples processed without errors."
echo "Have a look at the log files $OUTPUT and $ERRORS"