#!/bin/bash

# Run the proper commands for executing a constituent solver on a given COP.

SOLVER=$1
MZN=$2
DZN=$3
FZN=$4
OZN=$5
OUT=$6
TYPE=$7

OUTPUT_SCRIPT="$SUNNY_HOME/src/output_script"
SOLVERS_DIR="$SUNNY_HOME/solvers"
ADDITIONAL_PARAM=""

# No .dzn file is provided.
if 
  [ "$DZN" == 'NODATA' ]
then
  DZN=''
fi

# If file is a COP call the solver with -a parameter
if 
  [ "$DZN" == 'NODATA' ]
then
  DZN=''
fi

if 
  [ "$TYPE" == 'COP' ]
then
  ADDITIONAL_PARAM="-a $ADDITIONAL_PARAM"
fi
# For each constituent solver execute the corresponding commands: first the .mzn 
# is converted to the specific .fzn, and then the .fzn is run. 
# FIXME: Note that currently the output of each solver is 'commented' (by 
# prepending a % character) and redirected to a file using tee, for later being 
# properly processed by sunny-cp.

################################################################
# Commands to run the solvers of the MiniZinc suite
################################################################
if
  [ $SOLVER == "g12cbc" ]
then
  mzn2fzn -G linear $MZN $DZN -o $FZN --output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  flatzinc $ADDITIONAL_PARAM -b mip $FZN > $OUT 2> /dev/null
elif
  [ $SOLVER == "g12cpx" ]
then
  mzn2fzn -G g12_cpx $MZN $DZN -o $FZN --output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  fzn_cpx $ADDITIONAL_PARAM $FZN > $OUT 2> /dev/null
elif
  [ $SOLVER == "g12fd" ]
then
  mzn2fzn -G g12_fd $MZN $DZN -o $FZN --output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  flatzinc $ADDITIONAL_PARAM $FZN > $OUT 2> /dev/null
elif
  [ $SOLVER == "g12lazyfd" ]
then
  mzn2fzn -G g12_lazyfd $MZN $DZN -o $FZN --output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  flatzinc $ADDITIONAL_PARAM -b lazy $FZN > $OUT 2> /dev/null
else 
################################################################
# Commands to run other solvers of the MiniZinc suite
################################################################
  SOLVER_DIR=$SOLVERS_DIR/$SOLVER
  
  if [ ! -f "$SOLVER_DIR/fzn-exec" ]; then
    echo "The solver $SOLVER/fzn-exec was not found. Please verify its 
installation." >&2
    exit 1
  fi
  
  MZNLIB=""
  STDLIB=""
  
  if [ -d "$SOLVER_DIR/mzn-lib" ]; then
    MZNLIB="-I $SOLVER_DIR/mzn-lib"
  fi
  
  if [ -d "$SOLVER_DIR/stdlib" ]; then
    STDLIB="-I $SOLVER_DIR/stdlib"
  fi
  
  mzn2fzn $MZNLIB $STDLIB $MZN $DZN -o $FZN --output-ozn-to-file $OZN
  cp $OZN ~/log.log
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  else
    $SOLVER_DIR/fzn-exec $ADDITIONAL_PARAM $FZN > $OUT 2> /dev/null
  fi
fi