#!/bin/bash

# Run the proper commands for executing a constituent solver on a given CSP.

# FIXME: .ozn files are currently ignored, since we realized some bugs when 
# dealing with solns2out.

SOLVER=$1
MZN=$2
DZN=$3
FZN=$4
OZN=$5
OUT=$6

# No .dzn file is provided.
if 
  [ "$DZN" == 'NODATA' ]
then
  DZN=''
fi

# For each constituent solver execute the corresponding commands: first the .mzn 
# is converted to the specific .fzn, and then the .fzn is run. 
# FIXME: Note that currently the output of each solver is 'commented' (by 
# prepending a % character) and redirected to a file using tee, for later being 
# properly processed by sunny-cp.
if
  [ $SOLVER == "chuffed" ]
then
  MZNLIB=$HOME'/solvers/chuffed/mznlib'
  mzn2fzn $MZN $DZN -I $MZNLIB -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer fzn_chuffed $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "g12cbc" ]
then
  mzn2fzn -G linear $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer flatzinc -b mip $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "g12cpx" ]
then
  mzn2fzn -G g12_cpx $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer fzn_cpx $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "g12fd" ]
then
  mzn2fzn -G g12_fd $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer flatzinc $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "g12gurobi" ]
then
  mznlib=$HOME"/solvers/g12gur/lib/minizinc/linear"
  stdlib=$HOME"/solvers/g12gur/lib/minizinc/std"
  flatzinc=$HOME"/solvers/g12gur/bin/flatzinc"
  mzn2fzn -I $mznlib -I $stdlib $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer flatzinc -b mip $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "g12lazyfd" ]
then
  mzn2fzn -G g12_lazyfd $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer flatzinc -b lazy $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "gecode" ]
then
  MZNLIB=$HOME'/solvers/gecode-4.2.1/gecode/flatzinc/mznlib'
  mzn2fzn $MZN $DZN -I $MZNLIB -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer fzn-gecode $FZN | sed 's/^/% /' | tee $OUT
elif
  [ $SOLVER == "minisatid" ]
then
  mzn2fzn $MZN $DZN -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
  ret=$?
  if 
    [ $ret -ne 0 ]
  then
    echo "MiniZinc model not converted!" >&2
    exit $ret
  fi
  unbuffer minisatid -f=fz $FZN | sed 's/^/% /' | tee $OUT
# NOTE: Here is possible to add another constituent solver.
# elif
#   [ $SOLVER == "<solver name>" ]
# then
#   MZNLIB=<global redefinitions>
#   mzn2fzn $MZN $DZN -I $MZNLIB -o $FZN --no-output-ozn #--output-ozn-to-file $OZN
#   ret=$?
#   if 
#     [ $ret -ne 0 ]
#   then
#     echo "MiniZinc model not converted!" >&2
#     exit $ret
#   fi
#   unbuffer <solver command> $FZN | tee $OUT | sed 's/^/% /'
else
  echo "Error: undefined solver!" >&2
  exit 1
fi
