#!/bin/bash
# Scripts that process the output of the flatzinc solver

OUT=$1
# OZN=$2

while read line
do
#   if [ $line = "----------" ]
#   then
  echo $line | grep "o__b__j__v__a__r\|=====\|----------" >> $OUT 
  echo $line | grep -v "====="
done
